###
GET http://localhost:8080/api/floors/2
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzMyMjExOTA5LCJhdXRoIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzI5NjE5OTA5fQ.SiIQrIUHy-kA0AzbHo0o6Gc9WrjRZzIO_Z8316AUVSiYf8IduJXleL9aKyA_s-fwqFy7fZscbRXqDTGeoqAsXw
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczMjIxMjY0MCwiYXV0aCI6IlJPTEVfQURNSU4gUk9MRV9VU0VSIiwiaWF0IjoxNzI5NjIwNjQwfQ.A8djeccnKXFg-6JWQ1DmH0AtGpdTcfh4yxEsMw92-29vcUYemQ29vf4-gmOtsZuCOxMeyieXwuX2IdAUx1SRFQ




###
PUT http://localhost:8080/api/floors/update/2?name=999
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNzMyMjExOTA5LCJhdXRoIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzI5NjE5OTA5fQ.SiIQrIUHy-kA0AzbHo0o6Gc9WrjRZzIO_Z8316AUVSiYf8IduJXleL9aKyA_s-fwqFy7fZscbRXqDTGeoqAsXw
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImV4cCI6MTczMjIxMjY0MCwiYXV0aCI6IlJPTEVfQURNSU4gUk9MRV9VU0VSIiwiaWF0IjoxNzI5NjIwNjQwfQ.A8djeccnKXFg-6JWQ1DmH0AtGpdTcfh4yxEsMw92-29vcUYemQ29vf4-gmOtsZuCOxMeyieXwuX2IdAUx1SRFQ



